# Generated by Django 3.2.5 on 2022-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='device_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='serial_number',
            field=models.CharField(max_length=200),
        ),
    ]
