# Generated by Django 3.2.5 on 2022-08-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
