# Generated by Django 3.2.5 on 2022-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0005_connection_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='brand',
            field=models.CharField(choices=[('BOSCH', 'Bosch'), ('VAILLANT', 'Vaillant')], max_length=15),
        ),
    ]
