# Generated by Django 3.2.5 on 2022-08-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0006_alter_connection_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='heat_pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heat_pump.heatpump'),
        ),
    ]
