# Generated by Django 3.2.5 on 2022-08-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0007_connection_heat_pump'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['timestamp']},
        ),
    ]
