# Generated by Django 3.2.5 on 2022-08-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0009_alter_connection_heat_pump'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='api_key',
            new_name='access_token',
        ),
        migrations.AlterField(
            model_name='connection',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
