# Generated by Django 3.2.5 on 2022-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0011_auto_20220807_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='access_token',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='connection',
            name='refresh_token',
            field=models.CharField(max_length=2000),
        ),
    ]
