# Generated by Django 3.2.5 on 2022-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0012_auto_20220807_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpump',
            name='device_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='heatpump',
            name='serial_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
