# Generated by Django 3.2.5 on 2022-08-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0013_auto_20220807_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='heat_pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heat_pump.heatpump'),
            preserve_default=False,
        ),
    ]
