# Generated by Django 3.2.5 on 2022-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0014_alter_connection_heat_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpump',
            name='brand',
            field=models.CharField(choices=[('Bosch', 'Bosch'), ('Vaillant', 'Vaillant')], max_length=15),
        ),
    ]
