# Generated by Django 3.2.5 on 2022-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0015_alter_heatpump_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='brand',
            field=models.CharField(choices=[('Bosch', 'Bosch'), ('Vaillant', 'Vaillant')], max_length=15),
        ),
    ]
