# Generated by Django 3.2.5 on 2022-08-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0016_alter_connection_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='temp_set_point',
            new_name='temp_target',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='temp_outdoor',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
