# Generated by Django 3.2.5 on 2022-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_pump', '0017_auto_20220808_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='valid',
            new_name='expires_in',
        ),
    ]
