# Generated by Django 3.2.5 on 2022-08-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('type', models.CharField(choices=[('GAS', 'gas'), ('ELECTRICITY', 'electricity')], max_length=15)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
