# Generated by Django 3.2.5 on 2022-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='type',
            field=models.CharField(choices=[('gas', 'Gas'), ('electricity', 'Electricity')], max_length=15),
        ),
    ]
